#pragma once
#define QCAT_FAIL -1
#define QCAT_RELEASE 0
#define QCAT_PRESS 1
#define QCAT_REPEAT 2

#define QCAT_MOUSE_BUTTON_1         0
#define QCAT_MOUSE_BUTTON_2         1
#define QCAT_MOUSE_BUTTON_3         2
#define QCAT_MOUSE_BUTTON_4         3
#define QCAT_MOUSE_BUTTON_5         4
#define QCAT_MOUSE_BUTTON_6         5
#define QCAT_MOUSE_BUTTON_7         6
#define QCAT_MOUSE_BUTTON_8         7

#define QCAT_MOUSE_BUTTON_LAST      QCAT_MOUSE_BUTTON_8
#define QCAT_MOUSE_BUTTON_LEFT      QCAT_MOUSE_BUTTON_1
#define QCAT_MOUSE_BUTTON_RIGHT     QCAT_MOUSE_BUTTON_2
#define QCAT_MOUSE_BUTTON_MIDDLE    QCAT_MOUSE_BUTTON_3

//#define QCAT_DX11
#define QCAT_OPENGL